import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {randomBytes} from 'node:crypto';
import vm from 'node:vm';
const worker=(await import('../dist/server/index.js')).default;
const origin='https://nextlevel.example';
const database=new DatabaseSync(':memory:');
database.exec('PRAGMA foreign_keys=ON');
for(const file of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())database.exec(fs.readFileSync('drizzle/'+file,'utf8'));
function statement(sql,args=[]){return {bind(...values){return statement(sql,values);},async first(){return database.prepare(sql).get(...args)||null;},async all(){return {results:database.prepare(sql).all(...args)};},async run(){return database.prepare(sql).run(...args);}};}
const env={APP_ORIGIN:origin,GOOGLE_OAUTH_CLIENT_ID:"test-client",MAIL_SENDER:"nextleveletec@gmail.com",ADMIN_EMAIL:"admin@example.com",GMAIL_STORAGE_KEY:randomBytes(32).toString('base64url'),DB:{prepare:statement,async batch(statements){database.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());database.exec('COMMIT');return result;}catch(error){database.exec('ROLLBACK');throw error;}}},ASSETS:{fetch(){return new Response('asset');}}};
const mails=[];let failMail=false;
globalThis.fetch=async(url,init)=>{if(url.endsWith('/token'))return Response.json({access_token:'test-access',refresh_token:'test-refresh',scope:'https://www.googleapis.com/auth/gmail.send'});if(url.endsWith('/userinfo'))return Response.json({email:'nextleveletec@gmail.com',email_verified:true});if(url.endsWith('/messages/send')){if(failMail)return Response.json({error:'failed'},{status:500});mails.push(Buffer.from(JSON.parse(init.body).raw,'base64url').toString());return Response.json({id:'mail-'+mails.length});}throw Error('Unexpected external request');};
const adminHeaders={};
const adminSession='admin-test-session';
const adminUser='admin-test';
database.prepare('INSERT INTO users (id,email,name,birth_date,school,grade,address,password_hash,verified,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run(adminUser,'admin@example.com','Admin','1990-01-01','Outra escola (não ranqueada)','Admin','','unused',1,0);
database.prepare('INSERT INTO user_public_profiles (user_id,nick) VALUES (?,?)').run(adminUser,'TestAdmin');
database.prepare('INSERT INTO sessions (hash,user_id,expires_at) VALUES (?,?,?)').run(Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(adminSession))).toString('base64url'),adminUser,Math.floor(Date.now()/1000)+3600);
adminHeaders.cookie='__Host-nextlevel='+adminSession;
async function adminPost(path,data){const html=await (await worker.fetch(new Request(origin+'/admin/email',{headers:adminHeaders}),env)).text();const csrf=html.match(/name="csrf" value="([^"]+)"/)[1];return worker.fetch(new Request(origin+path,{method:'POST',headers:adminHeaders,body:new URLSearchParams({csrf,...data})}),env);}
await adminPost('/admin/email/credencial',{secret:'mock-secret'});
const connect=await adminPost('/admin/email/conectar',{}),oauthState=new URL(connect.headers.get('location')).searchParams.get('state');
assert.equal((await worker.fetch(new Request(origin+'/admin/email/retorno?state='+oauthState+'&code=test',{headers:adminHeaders}),env)).status,303);
database.prepare('DELETE FROM users WHERE id=?').run(adminUser);
function client(){let csrf='',cookies=new Map();return {async call(path,body,expected=200,extra={}){const headers={cookie:[...cookies].map(([k,v])=>k+'='+v).join('; '),...extra};if(body!==undefined)Object.assign(headers,{'content-type':'application/json','x-nextlevel-request':'1','x-nextlevel-csrf':csrf});const response=await worker.fetch(new Request(origin+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)}),env);for(const cookie of response.headers.getSetCookie()){const pair=cookie.split(';')[0],index=pair.indexOf('=');cookies.set(pair.slice(0,index),pair.slice(index+1));}const data=await response.json();assert.equal(response.status,expected,JSON.stringify({path,data}));if(data.csrf)csrf=data.csrf;return data;}};}
const a=client(),b=client(),c=client(),anonymous=client();
for(const person of [a,b,c,anonymous])assert.equal((await person.call('/api/conta')).user,null);
const registration=(name,email,nick=name)=>({name,nick,email,password:'strong-password-123',birthDate:'2010-07-18',school:'Escola Exemplo',grade:'9º ano',address:'Endereço privado 123'});
await anonymous.call('/api/cadastro',{...registration('Inválido','invalid@example.com'),birthDate:'2010-02-31'},400);
const invalidPassword=await a.call('/api/cadastro',{...registration('Ana','ana@example.com'),password:'12345'},400);
assert.match(invalidPassword.error,/mínimo de 6 caracteres/);
const noAddress={...registration('Ana','ana@example.com'),password:'123456',school:'  ESCOLA – BAIRRO, Cidade  '};delete noAddress.address;
function emailToken(email,kind){const mail=mails.findLast(x=>x.includes('To: '+email+'\r\n')&&x.includes('/conta?'+kind+'='));assert.ok(mail.includes(origin+'/conta?'));return new URL(mail.match(/https:\/\/\S+\/conta\?\S+/)[0]).searchParams.get(kind);}
const beforeRegistration=mails.length;
const registered=await a.call('/api/cadastro',noAddress,201);
assert.equal(registered.mailSent,false);assert.equal(mails.length,beforeRegistration);
let ana=(await a.call('/api/conta')).user;
assert.equal(ana.verified,true);assert.equal(ana.xp,0);assert.equal(ana.address,'');assert.equal(ana.school,noAddress.school);
assert.equal(ana.nick,'Ana');
assert.equal(database.prepare('SELECT verified FROM users WHERE id=?').get(ana.id).verified,1);
await b.call('/api/cadastro',registration('Bruno','bruno@example.com'),201);let bruno=(await b.call('/api/conta')).user;
await c.call('/api/cadastro',registration('Carol','carol@example.com'),201);let carol=(await c.call('/api/conta')).user;
assert.equal(bruno.nick,'Bruno');
const duplicateNick=await b.call('/api/perfil',{name:bruno.name,nick:'Ana',school:bruno.school,grade:bruno.grade},409);assert.match(duplicateNick.error,/nick já está em uso/);
// Legacy users are migrated once, preserving their password, address and XP.
database.prepare('UPDATE users SET verified=0 WHERE id=?').run(carol.id);
database.exec(fs.readFileSync('drizzle/0003_confirm_existing_users.sql','utf8'));
assert.equal(database.prepare('SELECT verified FROM users WHERE id=?').get(carol.id).verified,1);
assert.equal((await c.call('/api/conta')).user.verified,true);
// Even a stale legacy flag must never gate study, groups or public account data.
database.prepare('UPDATE users SET verified=0 WHERE id=?').run(bruno.id);
assert.equal((await b.call('/api/conta')).user.verified,true);
await b.call('/api/perfil',{name:bruno.name,school:bruno.school,grade:bruno.grade});
assert.equal((await b.call('/api/conta')).user.address,'Endereço privado 123');
await c.call('/api/perfil',{name:carol.name,school:'Outra escola (não ranqueada)',grade:carol.grade,address:'Não informado'});
assert.equal((await c.call('/api/conta')).user.address,'Não informado');
await anonymous.call('/api/ranking/alunos',undefined,401);
let ranking=await a.call('/api/ranking/alunos');assert.deepEqual(Object.keys(ranking.ranking[0]).sort(),['grade','nick','position','school','xp']);assert.equal(ranking.pagination.total,3);assert.equal(ranking.ranking.find(row=>row.nick==='Carol').school,'Outra escola (não ranqueada)');
ranking=await a.call('/api/ranking/alunos?page=2');assert.equal(ranking.ranking.length,0);assert.equal(ranking.pagination.page,2);
ranking=await a.call('/api/ranking/alunos?school=Escola%20Exemplo');assert.equal(ranking.pagination.total,1);assert.equal(ranking.ranking[0].nick,'Bruno');
ranking=await a.call('/api/ranking/classe');assert.equal(ranking.ranking.length,1);assert.equal(ranking.ranking[0].nick,'Ana');
ranking=await c.call('/api/ranking/classe');assert.equal(ranking.ranking.length,0);assert.match(ranking.aviso,/não ranqueada/);
ranking=await a.call('/api/ranking/escolas');assert.equal(ranking.pagination.total,2);assert.ok(ranking.ranking.every(row=>row.school!=='Outra escola (não ranqueada)'));assert.deepEqual(Object.keys(ranking.ranking[0]).sort(),['averageXp','position','school','students','totalXp']);
let me=await b.call('/api/ranking/eu');assert.deepEqual(Object.keys(me).sort(),['classPosition','generalPosition','groups','schoolPosition']);assert.equal(me.classPosition,1);assert.equal(me.groups.length,0);
await a.call('/api/reenviar',{});assert.equal(mails.length,beforeRegistration);
const created=await a.call('/api/grupos/criar',{name:'Turma Next Level',description:'Estudo com amigos',password:'grupo6'},201);
assert.equal(created.mailSent,true);assert.match(mails.at(-1),/To: ana@example.com\r\n/);assert.match(mails.at(-1),/https:\/\/nextlevel\.example\/convite\?/);
let detail=await a.call('/api/grupos/'+created.id),invite=new URL(detail.invite).searchParams.get('token');
assert.equal(detail.ranking.length,1);assert.equal(detail.ranking[0].name,'Ana');assert.equal(detail.ranking[0].xp,0);
await anonymous.call('/api/grupos/'+created.id,undefined,401);
await b.call('/api/grupos/'+created.id,undefined,403);
await b.call('/api/grupos/entrar',{token:invite,password:'incorrect-password'},400);
assert.equal((await b.call('/api/grupos/entrar',{token:invite,password:'grupo6'})).status,'pending');
await b.call('/api/grupos/'+created.id,undefined,403);
await b.call('/api/grupos/'+created.id+'/aprovar',{userId:bruno.id},403);
detail=await a.call('/api/grupos/'+created.id);assert.deepEqual(Object.keys(detail.pending[0]).sort(),['id','name']);
await a.call('/api/grupos/'+created.id+'/aprovar',{userId:bruno.id});
detail=await b.call('/api/grupos/'+created.id);assert.equal(detail.ranking.length,2);assert.equal(detail.invite,null);assert.equal(detail.pending.length,0);
for(const row of detail.ranking)assert.deepEqual(Object.keys(row).sort(),['id','name','xp']);
ranking=await a.call('/api/ranking/grupo/'+created.id);assert.equal(ranking.pagination.total,2);assert.deepEqual(Object.keys(ranking.ranking[0]).sort(),['grade','nick','position','school','xp']);await c.call('/api/ranking/grupo/'+created.id,undefined,403);
me=await b.call('/api/ranking/eu');assert.equal(me.groups.length,1);assert.equal(me.groups[0].position,2);
await b.call('/api/grupos/'+created.id+'/remover',{userId:ana.id},403);
const built=fs.readFileSync('dist/server/index.js','utf8');
const subjects=JSON.parse(built.match(/const STUDY_DATA=(.*);\nconst BOSS_DATA=/)[1]);
const boss=JSON.parse(built.match(/const BOSS_DATA=(.*);\n/)[1]);
const questions=new Map([...subjects.flatMap(s=>s.topics.flatMap(t=>t.pool)),...boss].map(q=>[q.key,q]));
const subject=subjects[0],topic=subject.topics[0],activity={kind:'duel',subject:subject.id,topic:topic.id};
const attempt=await b.call('/api/estudo/iniciar',activity);assert.equal(attempt.questions.length,12);assert.ok(attempt.questions.every(q=>!('answer' in q)));
const answers=attempt.questions.map(q=>{const original=questions.get(q.key);return original.options[original.answer];});
await a.call('/api/estudo/concluir',{id:attempt.id,answers},404);
await b.call('/api/estudo/concluir',{id:attempt.id,answers:Array(12).fill('forged-option')},400);
let score=await b.call('/api/estudo/concluir',{id:attempt.id,answers,xp:999999,correct:999999});assert.equal(score.correct,12);assert.equal(score.xp,120);assert.equal(score.gained,120);assert.equal(score.completed[subject.id+'-'+topic.id],true);
score=await b.call('/api/estudo/concluir',{id:attempt.id,answers});assert.equal(score.xp,120);assert.equal(score.repeated,true);
await b.call('/api/progresso',{xp:999999,completed:Object.fromEntries(subject.topics.map(t=>[subject.id+'-'+t.id,true])),theme:'quest'});
const progress=await b.call('/api/conta');assert.equal(progress.user.xp,120);assert.equal(progress.progress.theme,'quest');assert.equal(Object.keys(progress.progress.completed).length,1);
await b.call('/api/estudo/iniciar',{kind:'ranked',subject:subject.id},403);
async function ace(person,options){const attempt=await person.call('/api/estudo/iniciar',options);return person.call('/api/estudo/concluir',{id:attempt.id,answers:attempt.questions.map(q=>{const original=questions.get(q.key);return original.options[original.answer];})});}
score=await ace(b,{...activity,kind:'reading'});assert.equal(score.gained,20);assert.equal(score.xp,140);
score=await ace(b,{...activity,kind:'reading'});assert.equal(score.gained,0);assert.equal(score.xp,140);
detail=await a.call('/api/grupos/'+created.id);assert.equal(detail.ranking[0].name,'Bruno');assert.equal(detail.ranking[0].xp,140);
score=await ace(b,{kind:'boss'});assert.equal(score.total,180);assert.equal(score.gained,1800);assert.equal(score.xp,1940);
score=await ace(b,{kind:'boss'});assert.equal(score.gained,0);assert.equal(score.xp,1940);
me=await b.call('/api/ranking/eu');assert.equal(me.generalPosition,1);assert.equal(me.classPosition,1);assert.equal(me.schoolPosition,1);assert.equal(me.groups[0].position,1);
ranking=await a.call('/api/ranking/escolas');assert.equal(ranking.ranking.find(row=>row.school==='Escola Exemplo').totalXp,1940);assert.equal(ranking.ranking.find(row=>row.school==='Escola Exemplo').averageXp,1940);
await a.call('/api/grupos/'+created.id+'/convite',{password:'novo66'});
await c.call('/api/grupos/entrar',{token:invite,password:'grupo6'},400);
invite=new URL((await a.call('/api/grupos/'+created.id)).invite).searchParams.get('token');
await c.call('/api/grupos/entrar',{token:invite,password:'novo66'});
await a.call('/api/grupos/'+created.id+'/recusar',{userId:carol.id});
await c.call('/api/grupos/entrar',{token:invite,password:'novo66'},403);
await a.call('/api/grupos/'+created.id+'/remover',{userId:bruno.id});
await b.call('/api/grupos/'+created.id,undefined,403);
assert.equal((await a.call('/api/grupos/'+created.id)).ranking.length,1);
await a.call('/api/sair',{});await a.call('/api/conta');
await a.call('/api/entrar',{email:'ana@example.com',password:'wrong-password'},401);
await a.call('/api/entrar',{email:'ana@example.com',password:'123456'});await a.call('/api/conta');
await anonymous.call('/api/recuperar',{email:'ana@example.com'});
const reset=emailToken('ana@example.com','reset');
await anonymous.call('/api/redefinir',{token:reset,password:'12345'},400);
await anonymous.call('/api/redefinir',{token:reset,password:'novo66'});
await a.call('/api/grupos',undefined,401);await a.call('/api/conta');
await anonymous.call('/api/redefinir',{token:reset,password:'replacement-password-123'},400);
await a.call('/api/entrar',{email:'ana@example.com',password:'strong-password-123'},401);
await a.call('/api/entrar',{email:'ana@example.com',password:'novo66'});await a.call('/api/conta');
failMail=true;const persisted=await a.call('/api/grupos/criar',{name:'Grupo com e-mail indisponível',password:'another-password-123'},201);assert.equal(persisted.mailSent,false);assert.ok((await a.call('/api/grupos/'+persisted.id)).invite);
const stored=database.prepare('SELECT password_hash FROM users WHERE email=?').get('ana@example.com');assert.ok(!stored.password_hash.includes('replacement-password-123'));
console.log('Accounts passed: registration without confirmation, optional address, legacy verification migration, password reset/session revocation, private profile, creator approval, invitation rotation/removal, server grading, forged-XP rejection, idempotent XP and mail failure recovery.');
// Exercise the actual browser scripts against the same Worker and account.
const elements={app:{innerHTML:''},toast:{style:{}},'storage-warning':{hidden:true}};
const location=new URL(origin+'/grupos'),storage={};
const browser={console,Date,Math,Number,Array,Object,JSON,String,URLSearchParams,location,history:{replaceState(){}},setTimeout:()=>0,clearTimeout(){},scrollTo(){},alert(message){throw Error(message);},confirm:()=>true,localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>storage[k]=v},document:{documentElement:{setAttribute(){}},getElementById:id=>elements[id],body:{appendChild(){}},createElement:()=>({style:{}})},fetch:async(path,options)=>Response.json(await b.call(path,options.body?JSON.parse(options.body):undefined))};
browser.window=browser;vm.createContext(browser);
const html=fs.readFileSync('fixtures/web/index.html','utf8');
for(const match of html.matchAll(/<script(?: src="([^"]+)")?>([\s\S]*?)<\/script>/g))vm.runInContext(match[1]?fs.readFileSync('fixtures/web/'+match[1],'utf8'):match[2],browser);
for(let i=0;i<8;i++)await new Promise(resolve=>setImmediate(resolve));
assert.match(elements.app.innerHTML,/Meus grupos/);assert.match(elements.app.innerHTML,/Sair/);
const E=browser.NEXT_ENGINE,G=browser.RotaGame,R=browser.ReadingCheck,M=browser.NextModules;
assert.equal(E.state().xp,1940);
await G.startTopic(subject.id,topic.id);assert.equal(E.duel().questions.length,12);
for(let i=0;i<12;i++){const d=E.duel();G.answer(d.questions[d.index].answer);await G.nextQuestion();}
assert.equal(E.duel().phase,'victory');assert.equal(E.state().xp,(await b.call('/api/conta')).user.xp);
await G.startRevanche(subject.id,topic.id);assert.equal(E.duel().questions.length,12);
await R.start(subject.id,topic.id,true);
const check=E.state().readingChecks[subject.id+'-'+topic.id];
for(let i=0;i<4;i++){R.select(i);R.mark(check.questions[i].answer);}await R.submit();assert.equal(check.score,4);assert.equal(check.reward,0);
await M.startBoss(true);const draft=E.state().bossDraft;assert.equal(draft.order.length,180);assert.ok(draft.remoteId);
const by=new Map(browser.NEXT_BOSS.map(q=>[q.id,q]));for(let i=0;i<180;i++){M.selectBoss(i);M.markBoss(String.fromCharCode(65+by.get(draft.order[i]).answer));}
await M.submitBoss();assert.equal(draft.result.correct,180);assert.equal(draft.reward.xp,0);assert.equal(E.state().xp,(await b.call('/api/conta')).user.xp);
await browser.NextAccounts.page('account');assert.match(elements.app.innerHTML,/Sair/);assert.match(elements.app.innerHTML,/Endereço privado 123/);
console.log('Browser integration passed: account navigation, authenticated duel/revanche, reading check, Boss grading and authoritative XP.');
