import assert from 'node:assert/strict';import fs from 'node:fs';import {spawn,spawnSync} from 'node:child_process';import {randomBytes} from 'node:crypto';
const root=new URL('..',import.meta.url).pathname;process.chdir(root);
const temp='.wrangler/smoke';fs.mkdirSync(temp,{recursive:true});
const source=fs.readFileSync('dist/server/index.js','utf8').replace('const result=await fetch(url,{...init','const result=await testFetch(url,{...init').replace('export default {fetch(request,env){return runtime(env).fetch(request,env);}};',`export default {fetch(request,env){if(new URL(request.url).pathname==='/__test/mail')return Response.json({mail:lastMail});return runtime(env).fetch(request,env);}};`);
const mock=`let lastMail='';async function testFetch(url,init){if(url.endsWith('/token'))return Response.json({access_token:'mock',refresh_token:'mock-refresh',scope:'https://www.googleapis.com/auth/gmail.send'});if(url.endsWith('/userinfo'))return Response.json({email:'sender@example.com',email_verified:true});if(url.endsWith('/messages/send')){lastMail=new TextDecoder().decode(Uint8Array.from(atob(JSON.parse(init.body).raw.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)));return Response.json({id:'mock-message'});}throw Error('External network disabled in smoke test');}\n`;
fs.writeFileSync(temp+'/worker.mjs',mock+source);
fs.writeFileSync(temp+'/wrangler.toml',`name="nextlevel-local-test"\nmain="worker.mjs"\ncompatibility_date="2026-10-02"\n[assets]\ndirectory="../../public"\nbinding="ASSETS"\nrun_worker_first=true\n[[d1_databases]]\nbinding="DB"\ndatabase_name="nextlevel-local-test"\ndatabase_id="00000000-0000-0000-0000-000000000000"\n[vars]\nAPP_ORIGIN="http://127.0.0.1:8788"\nGOOGLE_OAUTH_CLIENT_ID="mock-client"\nMAIL_SENDER="sender@example.com"\nADMIN_EMAIL="admin@example.com"\nGMAIL_STORAGE_KEY="${randomBytes(32).toString('base64url')}"\n`);
const config=temp+'/wrangler.toml',persist=temp+'/state';
// Some restricted containers cannot enumerate interfaces; loopback-only dev remains sufficient.
let preload=[];try{(await import('node:os')).networkInterfaces();}catch{fs.writeFileSync(temp+'/loopback.cjs',"require('os').networkInterfaces=()=>({lo:[{address:'127.0.0.1',netmask:'255.0.0.0',family:'IPv4',mac:'00:00:00:00:00:00',internal:true,cidr:'127.0.0.1/8'}]});");preload=['--require',fs.realpathSync(temp+'/loopback.cjs')];}
fs.rmSync(persist,{recursive:true,force:true});
function wrangler(args){const r=spawnSync('node',['node_modules/wrangler/bin/wrangler.js',...args,'--config',config],{encoding:'utf8',env:{...process.env,WRANGLER_SEND_METRICS:'false'}});if(r.status!==0)throw Error(r.stderr+'\n'+r.stdout);return r.stdout;}
wrangler(['d1','execute','nextlevel-local-test','--local','--persist-to',persist,'--file','docs/SCHEMA.sql']);
const server=spawn('node',[...preload,'node_modules/wrangler/bin/wrangler.js','dev','--config',config,'--port','8788','--persist-to',persist],{stdio:['ignore','pipe','pipe'],env:{...process.env,WRANGLER_SEND_METRICS:'false'}});let logs='';server.stdout.on('data',d=>logs+=d);server.stderr.on('data',d=>logs+=d);
const origin='http://127.0.0.1:8788';
function client(){const cookies=new Map();let csrf='';return {async raw(path,body,form=false){const headers={cookie:[...cookies].map(([k,v])=>k+'='+v).join('; ')};if(body!==undefined){if(form)headers['content-type']='application/x-www-form-urlencoded';else Object.assign(headers,{'content-type':'application/json','x-nextlevel-request':'1','x-nextlevel-csrf':csrf});}const r=await fetch(origin+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:form?new URLSearchParams(body):JSON.stringify(body),redirect:'manual'});for(const c of r.headers.getSetCookie()){const [k,...v]=c.split(';')[0].split('=');cookies.set(k,v.join('='));}return r;},async call(path,body,status=200){const r=await this.raw(path,body);const d=await r.json();assert.equal(r.status,status,JSON.stringify({path,d}));if(d.csrf)csrf=d.csrf;return d;}};}
try{
 let ready=false;for(let i=0;i<150;i++){try{if((await fetch(origin+'/api/conta',{signal:AbortSignal.timeout(500)})).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,200));}assert.ok(ready,logs);
 const a=client(),b=client();for(const c of [a,b])await c.call('/api/conta');
 const registration=(name,email)=>({name,nick:name,email,password:'123456',birthDate:'2010-01-01',school:'Escola Local',grade:'9º'});
 await a.call('/api/cadastro',registration('Admin','admin@example.com'),201);await a.call('/api/conta');await b.call('/api/cadastro',registration('Aluno','student@example.com'),201);let student=(await b.call('/api/conta')).user;assert.equal(student.verified,true);assert.equal(student.address,'');
 let page=await a.raw('/admin/email');assert.equal(page.status,200);assert.equal((await b.raw('/admin/email')).status,403);assert.equal((await fetch(origin+'/admin/email',{headers:{'oai-authenticated-user-email':'admin@example.com'}})).status,403);
 const admin=async(path,data={})=>{const html=await (await a.raw('/admin/email')).text();return a.raw(path,{csrf:html.match(/name="csrf" value="([^"]+)"/)[1],...data},true);};
 assert.equal((await admin('/admin/email/credencial',{secret:'mock-client-secret'})).status,303);const connect=await admin('/admin/email/conectar');const url=new URL(connect.headers.get('location'));assert.equal((await a.raw('/admin/email/retorno?state='+url.searchParams.get('state')+'&code=mock')).status,303);
 await b.call('/api/recuperar',{email:'student@example.com'});const mail=(await (await fetch(origin+'/__test/mail')).json()).mail;assert.ok(mail.includes(origin+'/conta?reset='));const token=new URL(mail.match(/http:\/\/\S+\/conta\?\S+/)[0]).searchParams.get('reset');await b.call('/api/redefinir',{token,password:'novo66'});await b.call('/api/conta');await b.call('/api/entrar',{email:'student@example.com',password:'novo66'});await b.call('/api/conta');
 const subjects=JSON.parse(fs.readFileSync('data/study.json','utf8')),s=subjects[0],t=s.topics[0],qs=new Map(t.pool.map(q=>[q.key,q]));const round=await b.call('/api/estudo/iniciar',{kind:'duel',subject:s.id,topic:t.id});const score=await b.call('/api/estudo/concluir',{id:round.id,answers:round.questions.map(q=>{const o=qs.get(q.key);return o.options[o.answer];})});assert.equal(score.xp,120);
 const group=await a.call('/api/grupos/criar',{name:'Grupo Local',password:'grupo6'},201),detail=await a.call('/api/grupos/'+group.id);const invite=new URL(detail.invite).searchParams.get('token');await b.call('/api/grupos/entrar',{token:invite,password:'grupo6'});await a.call('/api/grupos/'+group.id+'/aprovar',{userId:student.id});
 for(const path of ['/api/ranking/alunos','/api/ranking/escolas','/api/ranking/classe','/api/ranking/eu','/api/ranking/grupo/'+group.id])await b.call(path);
 assert.equal((await b.call('/api/ranking/grupo/'+group.id)).ranking[0].xp,120);
 console.log('WRANGLER LOCAL PASSOU: D1 vazio, cadastro, login, admin por sessão, rejeição oai, recuperação/redefinição sem envio real, rodada +120 XP, grupos/aprovação e 5 rankings.');
}finally{server.kill('SIGTERM');}
