// Account and group routes. Included in the Worker by the build script.
const accountCookie='__Host-nextlevel';
const accountSeconds=60*60*24*14;
const accountRankingPageSize=50;
function accountJSON(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...headers}});}
function accountCookieValue(request,name){return request.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)||'';}
function accountSetCookie(name,value,seconds){return name+'='+value+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age='+seconds;}
function accountQuery(env,sql,...args){return db(env).prepare(sql).bind(...args);}
async function accountRate(env,key,max,seconds){const t=now();const row=await accountQuery(env,'INSERT INTO rate_limits (key,count,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires_at<=? THEN 1 ELSE count+1 END,expires_at=CASE WHEN expires_at<=? THEN excluded.expires_at ELSE expires_at END RETURNING count',key,t+seconds,t,t).first();if(row.count>max)throw new Failure(429,'Muitas tentativas. Aguarde alguns minutos e tente novamente.');}
async function accountHash(password,salt=random(16)){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:unb64(salt),iterations:100000,hash:'SHA-256'},key,256);return salt+'.'+b64(new Uint8Array(bits));}
async function accountPasswordMatches(password,hash){const computed=await accountHash(password,hash.split('.')[0]);if(computed.length!==hash.length)return false;let difference=0;for(let i=0;i<hash.length;i++)difference|=computed.charCodeAt(i)^hash.charCodeAt(i);return difference===0;}
function accountPassword(value){if(typeof value!=='string'||value.length<6||value.length>128)throw new Failure(400,'Use uma senha com mínimo de 6 caracteres e máximo de 128.');return value;}
function accountText(value,max,min=1){if(typeof value!=='string'||value.trim().length<min||value.length>max)throw new Failure(400,'Confira os campos obrigatórios e seus tamanhos.');return value.trim();}
// Future school rankings must exclude users whose school equals GENERIC_SCHOOL.
const GENERIC_SCHOOL='Outra escola (não ranqueada)';
function accountSchool(value){accountText(value,160);return value;}
function accountAddress(value){return accountText(value===undefined?'':value,250,0);}
function accountEmail(value){const email=accountText(value,254).toLowerCase();if(!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(email))throw new Failure(400,'Informe um e-mail válido.');return email;}
async function accountUser(request,env,required=true){const raw=accountCookieValue(request,accountCookie);const u=raw?await accountQuery(env,'SELECT u.*,s.hash AS session_hash,p.nick AS public_nick FROM sessions s JOIN users u ON u.id=s.user_id JOIN user_public_profiles p ON p.user_id=u.id WHERE s.hash=? AND s.expires_at>?',await digest(raw),now()).first():null;if(!u&&required)throw new Failure(401,'Entre na sua conta para continuar.');return u;}
function accountPublicUser(u,xp){return {id:u.id,email:u.email,name:u.name,nick:u.public_nick,birthDate:u.birth_date,school:u.school,grade:u.grade,address:u.address,verified:true,xp};}
async function accountXP(env,id){return (await accountQuery(env,'SELECT COALESCE(SUM(xp),0) AS xp FROM xp_ledger WHERE user_id=?',id).first()).xp;}
function accountRankingPage(url){const raw=url.searchParams.get('page')||'1';if(!/^[1-9]\d*$/.test(raw))throw new Failure(400,'Informe uma página válida.');const page=Number(raw);if(!Number.isSafeInteger(page)||page>Math.floor(Number.MAX_SAFE_INTEGER/accountRankingPageSize))throw new Failure(400,'Informe uma página válida.');return {page,pageSize:accountRankingPageSize,offset:(page-1)*accountRankingPageSize};}
function accountRankingPagination(page,total){return {page,pageSize:accountRankingPageSize,total,pages:Math.ceil(total/accountRankingPageSize)};}
let accountNickSchemaReady;
async function accountEnsureNickSchema(env){if(!accountNickSchemaReady)accountNickSchemaReady=(async()=>{await accountQuery(env,'CREATE TABLE IF NOT EXISTS user_public_profiles (user_id TEXT PRIMARY KEY NOT NULL REFERENCES users(id) ON DELETE CASCADE, nick TEXT NOT NULL COLLATE NOCASE UNIQUE)').run();await accountQuery(env,"INSERT OR IGNORE INTO user_public_profiles (user_id,nick) SELECT u.id,'Aluno'||substr(lower(hex(randomblob(6))),1,10) FROM users u LEFT JOIN user_public_profiles p ON p.user_id=u.id WHERE p.user_id IS NULL").run();})().catch(error=>{accountNickSchemaReady=null;throw error;});return accountNickSchemaReady;}
async function accountNickname(env,value,currentId){let nick=value===undefined||value===null||value===''?'Aluno'+random(8).replace(/[^A-Za-z0-9]/g,'').slice(0,10):accountText(value,16,3);if(!/^[A-Za-z0-9_]{3,16}$/.test(nick))throw new Failure(400,'Use um nick de 3 a 16 caracteres, apenas letras, números e _.');const duplicate=await accountQuery(env,'SELECT user_id FROM user_public_profiles WHERE nick=? COLLATE NOCASE AND user_id<>?',nick,currentId||'').first();if(duplicate)throw new Failure(409,'Este nick já está em uso. Escolha outro.');return nick;}
async function accountRankingStudents(env,filters,page){const where=filters.map(f=>'u.'+f.column+' = ?').join(' AND ')||'1=1',args=filters.map(f=>f.value);const count=await accountQuery(env,'SELECT COUNT(*) AS total FROM users u WHERE '+where,...args).first();const rows=await accountQuery(env,`WITH scores AS (SELECT u.id,p.nick,u.school,u.grade,COALESCE(SUM(x.xp),0) AS xp FROM users u JOIN user_public_profiles p ON p.user_id=u.id LEFT JOIN xp_ledger x ON x.user_id=u.id WHERE ${where} GROUP BY u.id,p.nick), ranked AS (SELECT ROW_NUMBER() OVER (ORDER BY xp DESC,nick COLLATE NOCASE,id) AS position,nick,school,grade,xp FROM scores) SELECT position,nick,school,grade,xp FROM ranked ORDER BY position LIMIT ? OFFSET ?`,...args,accountRankingPageSize,page.offset).all();return {ranking:rows.results,pagination:accountRankingPagination(page.page,count.total)};}
async function accountRankingPosition(env,filters,userId){const where=filters.map(f=>'u.'+f.column+' = ?').join(' AND ')||'1=1',args=filters.map(f=>f.value);const row=await accountQuery(env,`SELECT position FROM (SELECT u.id,ROW_NUMBER() OVER (ORDER BY COALESCE(SUM(x.xp),0) DESC,p.nick COLLATE NOCASE,u.id) AS position FROM users u JOIN user_public_profiles p ON p.user_id=u.id LEFT JOIN xp_ledger x ON x.user_id=u.id WHERE ${where} GROUP BY u.id,p.nick) WHERE id=?`,...args,userId).first();return row?.position??null;}
async function accountSession(env,id){const raw=random(32);await accountQuery(env,'INSERT INTO sessions (hash,user_id,expires_at) VALUES (?,?,?)',await digest(raw),id,now()+accountSeconds).run();return accountSetCookie(accountCookie,raw,accountSeconds);}
async function accountMail(env,user,subject,message){await accountRate(env,'mail:'+user.id,6,3600);const cfg=await settings(env);if(!cfg?.refresh_token||cfg.sender!==SENDER)throw new Failure(503,'O envio de e-mail está indisponível. Tente reenviar mais tarde.');const tokens=await tokenRequest({client_id:CLIENT_ID,client_secret:await open(cfg.client_secret,env),refresh_token:await open(cfg.refresh_token,env),grant_type:'refresh_token'});const mime='From: Next Level <'+SENDER+'>\r\nTo: '+user.email+'\r\nSubject: =?UTF-8?B?'+btoa(String.fromCharCode(...enc.encode(subject)))+'?=\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n'+message;const result=await googleJSON('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',headers:{authorization:'Bearer '+tokens.access_token,'content-type':'application/json'},body:JSON.stringify({raw:b64(enc.encode(mime))})});if(!result.id)throw new Failure(502,'O Gmail não confirmou o envio.');}
async function accountSendToken(env,user,kind){const raw=random(32);await accountQuery(env,'DELETE FROM account_tokens WHERE user_id=? AND kind=?',user.id,kind).run();await accountQuery(env,'INSERT INTO account_tokens (hash,user_id,kind,expires_at) VALUES (?,?,?,?)',await digest(raw),user.id,kind,now()+(kind==='verify'?86400:1800)).run();const link=ORIGIN+'/conta?'+kind+'='+encodeURIComponent(raw);await accountMail(env,user,kind==='verify'?'Confirme sua conta no Next Level':'Redefina sua senha do Next Level',(kind==='verify'?'Confirme seu e-mail para participar dos grupos:':'Crie uma nova senha (link válido por 30 minutos):')+'\n\n'+link+'\n\nSe você não fez esta solicitação, ignore esta mensagem.');}
const accountAllowedState=['wrongLog','examDrafts','examResults','bossDraft','bossResults','readingChecks','usedIdx','rankedCleared','theme','mode'];
async function accountBootstrap(request,env){const u=await accountUser(request,env,false);if(u){const xp=await accountXP(env,u.id);return accountJSON({user:accountPublicUser(u,xp),csrf:await csrf(env,u.session_hash),progress:{...JSON.parse(u.saved_state),completed:JSON.parse(u.completed),xp}});}let nonce=accountCookieValue(request,'__Host-nextlevel-form');let headers={};if(!/^[\w-]{43}$/.test(nonce)){nonce=random(32);headers['set-cookie']=accountSetCookie('__Host-nextlevel-form',nonce,3600);}return accountJSON({user:null,csrf:await csrf(env,nonce)},200,headers);}
async function accountBody(request,env,u){if(!request.headers.get('content-type')?.startsWith('application/json')||request.headers.get('x-nextlevel-request')!=='1')throw new Failure(403,'Solicitação não permitida.');const text=await request.text();if(text.length>260000)throw new Failure(413,'Solicitação muito grande.');let body;try{body=JSON.parse(text);}catch{throw new Failure(400,'Solicitação inválida.');}const identity=u?.session_hash||accountCookieValue(request,'__Host-nextlevel-form');const token=request.headers.get('x-nextlevel-csrf')||'',t=Number(token.split('.')[0]);if(!identity||!Number.isInteger(t)||t<now()-3600||t>now()+30||token!==await csrf(env,identity,t))throw new Failure(403,'Sua sessão expirou. Atualize a página.');return body;}
async function accountGroup(env,id,u,creator=false){const g=await accountQuery(env,'SELECT * FROM study_groups WHERE id=?',id).first();if(!g)throw new Failure(404,'Grupo não encontrado.');if(creator&&g.owner_id!==u.id)throw new Failure(403,'Somente o criador pode gerenciar este grupo.');if(!creator&&g.owner_id!==u.id){const member=await accountQuery(env,'SELECT status FROM group_members WHERE id=?',id+'|'+u.id).first();if(member?.status!=='approved')throw new Failure(403,'Sua entrada precisa ser aprovada para acessar o grupo.');}return g;}
async function accountGroupMail(env,g,u){const token=await open(g.invite_secret,env);await accountMail(env,u,'Seu convite de grupo — Next Level','Seu grupo '+g.name+' foi criado.\n\nCompartilhe este link apenas com quem você quer convidar:\n'+ORIGIN+'/convite?token='+encodeURIComponent(token)+'\n\nEnvie a senha do grupo separadamente. A entrada depende da sua aprovação em Meus grupos.');}
function accountQuestions(kind,subject,topic){if(kind==='boss')return BOSS_DATA;const s=STUDY_DATA.find(x=>x.id===subject);if(!s)throw new Failure(400,'Matéria inválida.');if(kind==='ranked')return s.topics.flatMap(x=>x.pool);const t=s.topics.find(x=>x.id===topic);if(!t)throw new Failure(400,'Tópico inválido.');return t.pool;}
function accountQuestionById(id){return STUDY_DATA.flatMap(s=>s.topics.flatMap(t=>t.pool)).find(x=>x.key===id)||BOSS_DATA.find(x=>x.key===id);}
function accountShuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=crypto.getRandomValues(new Uint32Array(1))[0]%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
async function accountStudyStart(env,u,b){if(!['duel','reading','ranked','boss'].includes(b.kind))throw new Failure(400,'Atividade inválida.');await accountRate(env,'study-start:'+u.id,80,3600);const completed=JSON.parse(u.completed),s=STUDY_DATA.find(x=>x.id===b.subject);if(b.kind==='duel'){const index=s?.topics.findIndex(x=>x.id===b.topic);if(index>0&&!completed[s.id+'-'+s.topics[index-1].id]&&!completed[s.id+'-'+b.topic])throw new Failure(403,'Domine o tópico anterior para liberar este duelo.');}if(b.kind==='ranked'&&(!s||!s.topics.every(t=>completed[s.id+'-'+t.id])))throw new Failure(403,'Domine os tópicos da matéria antes da ranqueada.');let pool=accountQuestions(b.kind,b.subject,b.topic);if(b.previous){const prior=await accountQuery(env,'SELECT question_ids FROM study_attempts WHERE id=? AND user_id=? AND kind=? AND subject=? AND topic=?',b.previous,u.id,b.kind,b.subject,b.topic).first();if(prior){const ids=new Set(JSON.parse(prior.question_ids));const fresh=pool.filter(q=>!ids.has(q.key));if(fresh.length>=(b.kind==='reading'?4:12))pool=fresh;}}const count=b.kind==='reading'?4:b.kind==='ranked'?15:b.kind==='boss'?180:12,qs=accountShuffle(pool).slice(0,count),id=crypto.randomUUID();await accountQuery(env,'INSERT INTO study_attempts (id,user_id,kind,subject,topic,question_ids,created_at,submitted) VALUES (?,?,?,?,?,?,?,0)',id,u.id,b.kind,b.subject||null,b.topic||null,JSON.stringify(qs.map(q=>q.key)),now()).run();return accountJSON({id,kind:b.kind,questions:qs.map(q=>({key:q.key,prompt:q.prompt,options:q.options,bossId:q.bossId}))});}
async function accountStudySubmit(env,u,b){const attempt=await accountQuery(env,'SELECT * FROM study_attempts WHERE id=? AND user_id=?',b.id,u.id).first();if(!attempt)throw new Failure(404,'Atividade não encontrada.');if(attempt.submitted)return accountJSON({...JSON.parse(attempt.result),xp:await accountXP(env,u.id),repeated:true});if(attempt.created_at<now()-86400)throw new Failure(400,'Atividade expirada. Inicie uma nova rodada.');const qs=JSON.parse(attempt.question_ids).map(accountQuestionById);if(!Array.isArray(b.answers)||b.answers.length!==qs.length||b.answers.some((a,i)=>a!==null&&(typeof a!=='string'||!qs[i].options.includes(a))))throw new Failure(400,'Respostas inválidas.');if(['reading','duel'].includes(attempt.kind)&&b.answers.includes(null))throw new Failure(400,'Responda todas as perguntas antes de finalizar.');const correct=qs.filter((q,i)=>q.options[q.answer]===b.answers[i]).length,passed=attempt.kind==='reading'?correct>=3:attempt.kind==='duel'?correct>=10:attempt.kind==='ranked'?correct===15:false,earned=[];if(attempt.kind==='reading'){if(passed)earned.push({key:'reading:'+attempt.subject+':'+attempt.topic,xp:20});}else qs.forEach((q,i)=>{if(q.options[q.answer]===b.answers[i])earned.push({key:q.key,xp:10});});const before=await accountXP(env,u.id),result={correct,total:qs.length,blank:b.answers.filter(x=>x===null).length,percentage:Math.round(correct/qs.length*100),passed};const statements=earned.map(e=>accountQuery(env,'INSERT OR IGNORE INTO xp_ledger (id,user_id,activity_key,xp,earned_at) SELECT ?,?,?,?,? WHERE EXISTS (SELECT 1 FROM study_attempts WHERE id=? AND user_id=? AND submitted=0)',u.id+'|'+e.key,u.id,e.key,e.xp,now(),attempt.id,u.id));if(passed&&attempt.kind==='duel')statements.push(accountQuery(env,"UPDATE users SET completed=json_set(completed,?,json('true')) WHERE id=? AND EXISTS (SELECT 1 FROM study_attempts WHERE id=? AND user_id=? AND submitted=0)",'$."'+attempt.subject+'-'+attempt.topic+'"',u.id,attempt.id,u.id));statements.push(accountQuery(env,'UPDATE study_attempts SET submitted=1,result=? WHERE id=? AND user_id=? AND submitted=0',JSON.stringify(result),attempt.id,u.id));await db(env).batch(statements);const xp=await accountXP(env,u.id),fresh=await accountQuery(env,'SELECT completed FROM users WHERE id=?',u.id).first();return accountJSON({...result,xp,gained:xp-before,completed:JSON.parse(fresh.completed)});}
async function accountRoutes(request,env){const url=new URL(request.url),path=url.pathname;try{db(env);await accountEnsureNickSchema(env);if(request.method==='GET'&&path==='/api/conta')return await accountBootstrap(request,env);const u=await accountUser(request,env,!['/api/cadastro','/api/entrar','/api/recuperar','/api/redefinir'].includes(path));if(request.method==='GET'){
 if(path==='/api/ranking/alunos'){const page=accountRankingPage(url),school=url.searchParams.get('school');if(school!==null&&school.length>160)throw new Failure(400,'A escola deve ter até 160 caracteres.');return accountJSON(await accountRankingStudents(env,school===null?[]:[{column:'school',value:school}],page));}
 if(path==='/api/ranking/escolas'){const page=accountRankingPage(url),count=await accountQuery(env,'SELECT COUNT(*) AS total FROM (SELECT school FROM users WHERE school<>? GROUP BY school)',GENERIC_SCHOOL).first();const rows=await accountQuery(env,`WITH schools AS (SELECT u.school,COUNT(DISTINCT u.id) AS students,COALESCE(SUM(x.xp),0) AS totalXp,ROUND(COALESCE(SUM(x.xp),0)*1.0/COUNT(DISTINCT u.id),2) AS averageXp FROM users u LEFT JOIN xp_ledger x ON x.user_id=u.id WHERE u.school<>? GROUP BY u.school), ranked AS (SELECT ROW_NUMBER() OVER (ORDER BY totalXp DESC,school COLLATE NOCASE) AS position,school,students,totalXp,averageXp FROM schools) SELECT position,school,students,totalXp,averageXp FROM ranked ORDER BY position LIMIT ? OFFSET ?`,GENERIC_SCHOOL,accountRankingPageSize,page.offset).all();return accountJSON({ranking:rows.results,pagination:accountRankingPagination(page.page,count.total)});}
 if(path==='/api/ranking/classe'){const page=accountRankingPage(url);if(u.school===GENERIC_SCHOOL)return accountJSON({ranking:[],aviso:'Sua escola está marcada como não ranqueada; o ranking da classe não está disponível.',pagination:accountRankingPagination(page.page,0)});return accountJSON(await accountRankingStudents(env,[{column:'school',value:u.school},{column:'grade',value:u.grade}],page));}
 if(path==='/api/ranking/eu'){const generalPosition=await accountRankingPosition(env,[],u.id),classPosition=u.school===GENERIC_SCHOOL?null:await accountRankingPosition(env,[{column:'school',value:u.school},{column:'grade',value:u.grade}],u.id);let schoolPosition=null;if(u.school!==GENERIC_SCHOOL){const school=await accountQuery(env,`WITH schools AS (SELECT u.school,COALESCE(SUM(x.xp),0) AS totalXp FROM users u LEFT JOIN xp_ledger x ON x.user_id=u.id WHERE u.school<>? GROUP BY u.school), ranked AS (SELECT school,ROW_NUMBER() OVER (ORDER BY totalXp DESC,school COLLATE NOCASE) AS position FROM schools) SELECT position FROM ranked WHERE school=?`,GENERIC_SCHOOL,u.school).first();schoolPosition=school?.position??null;}const groups=await accountQuery(env,`WITH scores AS (SELECT m.group_id,g.name AS group_name,u.id,p.nick,COALESCE(SUM(x.xp),0) AS xp FROM group_members m JOIN study_groups g ON g.id=m.group_id JOIN users u ON u.id=m.user_id JOIN user_public_profiles p ON p.user_id=u.id LEFT JOIN xp_ledger x ON x.user_id=u.id WHERE m.status='approved' AND m.group_id IN (SELECT group_id FROM group_members WHERE user_id=? AND status='approved') GROUP BY m.group_id,u.id,p.nick), ranked AS (SELECT group_id,group_name,id,ROW_NUMBER() OVER (PARTITION BY group_id ORDER BY xp DESC,nick COLLATE NOCASE,id) AS position FROM scores) SELECT group_id AS id,group_name AS name,position FROM ranked WHERE id=? ORDER BY group_name COLLATE NOCASE,group_id`,u.id,u.id).all();return accountJSON({generalPosition,classPosition,schoolPosition,...(u.school===GENERIC_SCHOOL?{classAviso:'Sua escola está marcada como não ranqueada; o ranking da classe não está disponível.'}:{}),groups:groups.results});}
 const rankingGroupMatch=path.match(/^\/api\/ranking\/grupo\/([\w-]+)$/);if(rankingGroupMatch){const page=accountRankingPage(url),group=await accountGroup(env,rankingGroupMatch[1],u),count=await accountQuery(env,"SELECT COUNT(*) AS total FROM group_members WHERE group_id=? AND status='approved'",group.id).first();const rows=await accountQuery(env,`WITH scores AS (SELECT u.id,p.nick,u.school,u.grade,COALESCE(SUM(x.xp),0) AS xp FROM group_members m JOIN users u ON u.id=m.user_id JOIN user_public_profiles p ON p.user_id=u.id LEFT JOIN xp_ledger x ON x.user_id=u.id WHERE m.group_id=? AND m.status='approved' GROUP BY u.id,p.nick), ranked AS (SELECT ROW_NUMBER() OVER (ORDER BY xp DESC,nick COLLATE NOCASE,id) AS position,nick,school,grade,xp FROM scores) SELECT position,nick,school,grade,xp FROM ranked ORDER BY position LIMIT ? OFFSET ?`,group.id,accountRankingPageSize,page.offset).all();return accountJSON({ranking:rows.results,pagination:accountRankingPagination(page.page,count.total)});}
 if(path==='/api/grupos'){const rows=await accountQuery(env,'SELECT g.id,g.name,g.description,g.owner_id,m.status FROM study_groups g JOIN group_members m ON m.group_id=g.id WHERE m.user_id=? ORDER BY g.created_at DESC',u.id).all();return accountJSON({groups:rows.results.map(g=>({...g,creator:g.owner_id===u.id}))});}
 const match=path.match(/^\/api\/grupos\/([\w-]+)$/);if(match){const g=await accountGroup(env,match[1],u),creator=g.owner_id===u.id;const rows=await accountQuery(env,"SELECT u.id,p.nick AS name,COALESCE(SUM(x.xp),0) AS xp FROM group_members m JOIN users u ON u.id=m.user_id JOIN user_public_profiles p ON p.user_id=u.id LEFT JOIN xp_ledger x ON x.user_id=u.id WHERE m.group_id=? AND m.status='approved' GROUP BY u.id,p.nick ORDER BY xp DESC,p.nick COLLATE NOCASE,u.id",g.id).all();const pending=creator?await accountQuery(env,"SELECT u.id,p.nick AS name FROM group_members m JOIN users u ON u.id=m.user_id JOIN user_public_profiles p ON p.user_id=u.id WHERE m.group_id=? AND m.status='pending' ORDER BY m.requested_at",g.id).all():{results:[]};return accountJSON({group:{id:g.id,name:g.name,description:g.description,creator},ranking:rows.results,pending:pending.results,invite:creator?ORIGIN+'/convite?token='+encodeURIComponent(await open(g.invite_secret,env)):null});}
 throw new Failure(404,'Página não encontrada.');
 }if(request.method!=='POST')throw new Failure(405,'Método não permitido.');const b=await accountBody(request,env,u);const peer=request.headers.get('cf-connecting-ip')||'shared';
 if(path==='/api/cadastro'){await accountRate(env,'register:'+peer,8,3600);const email=accountEmail(b.email),name=accountText(b.name,80),nick=await accountNickname(env,b.nick),school=accountSchool(b.school),grade=accountText(b.grade,40),address=accountAddress(b.address),birth=accountText(b.birthDate,10),password=accountPassword(b.password);if(!/^\d{4}-\d{2}-\d{2}$/.test(birth)||!Number.isFinite(Date.parse(birth))||new Date(birth).toISOString().slice(0,10)!==birth||new Date(birth)>new Date()||new Date(birth)<new Date('1900-01-01'))throw new Failure(400,'Confira sua data de nascimento.');const existing=await accountQuery(env,'SELECT id FROM users WHERE email=?',email).first();if(existing)throw new Failure(409,'Este e-mail já tem cadastro. Entre ou recupere sua senha.');const id=crypto.randomUUID();await db(env).batch([accountQuery(env,'INSERT INTO users (id,email,name,birth_date,school,grade,address,password_hash,verified,created_at) VALUES (?,?,?,?,?,?,?,?,1,?)',id,email,name,birth,school,grade,address,await accountHash(password),now()),accountQuery(env,'INSERT INTO user_public_profiles (user_id,nick) VALUES (?,?)',id,nick)]);return accountJSON({ok:true,mailSent:false},201,{'set-cookie':await accountSession(env,id)});}
 if(path==='/api/entrar'){const email=accountEmail(b.email);await accountRate(env,'login:'+await digest(peer+'|'+email),10,900);const user=await accountQuery(env,'SELECT * FROM users WHERE email=?',email).first();const hash=user?.password_hash||await accountHash('unused-default-password',b64(new Uint8Array(16)));const password=accountPassword(b.password);if(!await accountPasswordMatches(password,hash)||!user)throw new Failure(401,'E-mail ou senha incorretos.');return accountJSON({ok:true},200,{'set-cookie':await accountSession(env,user.id)});}
 if(path==='/api/recuperar'){const email=accountEmail(b.email);await accountRate(env,'reset:'+await digest(peer+'|'+email),3,3600);const user=await accountQuery(env,'SELECT * FROM users WHERE email=?',email).first();if(user)await accountSendToken(env,user,'reset');return accountJSON({ok:true,message:'Se houver uma conta com este e-mail, você receberá o link de recuperação.'});}
 if(path==='/api/redefinir'||path==='/api/verificar'){const kind=path==='/api/verificar'?'verify':'reset',hash=await digest(accountText(b.token,100)),t=await accountQuery(env,'SELECT * FROM account_tokens WHERE hash=? AND kind=? AND expires_at>?',hash,kind,now()).first();if(!t)throw new Failure(400,'Link expirado ou já usado. Solicite outro.');if(kind==='verify'&&t.user_id!==u.id)throw new Failure(403,'Entre na conta correspondente ao e-mail deste link.');const changes=kind==='verify'?[accountQuery(env,"UPDATE users SET verified=1 WHERE id=? AND EXISTS (SELECT 1 FROM account_tokens WHERE hash=?)",t.user_id,hash)]:[accountQuery(env,'UPDATE users SET password_hash=? WHERE id=? AND EXISTS (SELECT 1 FROM account_tokens WHERE hash=?)',await accountHash(accountPassword(b.password)),t.user_id,hash),accountQuery(env,'DELETE FROM sessions WHERE user_id=?',t.user_id)];changes.push(accountQuery(env,'DELETE FROM account_tokens WHERE hash=?',hash));await db(env).batch(changes);return accountJSON({ok:true});}
 if(path==='/api/reenviar'){return accountJSON({ok:true});}
 if(path==='/api/sair'){await accountQuery(env,'DELETE FROM sessions WHERE hash=?',u.session_hash).run();return accountJSON({ok:true},200,{'set-cookie':accountSetCookie(accountCookie,'',0)});}
 if(path==='/api/perfil'){const name=accountText(b.name,80),nick=await accountNickname(env,b.nick===undefined?u.public_nick:b.nick,u.id),school=accountSchool(b.school),grade=accountText(b.grade,40),address=b.address===undefined?u.address:accountAddress(b.address);await db(env).batch([accountQuery(env,'UPDATE users SET name=?,school=?,grade=?,address=? WHERE id=?',name,school,grade,address,u.id),accountQuery(env,'UPDATE user_public_profiles SET nick=? WHERE user_id=?',nick,u.id)]);return accountJSON({ok:true});}
 if(path==='/api/progresso'){const state={};for(const key of accountAllowedState)if(key in b)state[key]=b[key];const payload=JSON.stringify(state);if(payload.length>250000)throw new Failure(413,'Rascunho muito grande.');await accountQuery(env,'UPDATE users SET saved_state=? WHERE id=?',payload,u.id).run();return accountJSON({ok:true});}
 if(path==='/api/estudo/iniciar')return await accountStudyStart(env,u,b);
 if(path==='/api/estudo/concluir')return await accountStudySubmit(env,u,b);
 if(path==='/api/grupos/criar'){await accountRate(env,'create-group:'+u.id,10,86400);const name=accountText(b.name,80),description=accountText(b.description||'',300,0),password=accountPassword(b.password),id=crypto.randomUUID(),invite=random(32);await db(env).batch([accountQuery(env,'INSERT INTO study_groups (id,owner_id,name,description,password_hash,invite_hash,invite_secret,created_at) VALUES (?,?,?,?,?,?,?,?)',id,u.id,name,description,await accountHash(password),await digest(invite),await seal(invite,env),now()),accountQuery(env,'INSERT INTO group_members (id,group_id,user_id,status,requested_at) VALUES (?,?,?,?,?)',id+'|'+u.id,id,u.id,'approved',now())]);const g=await accountQuery(env,'SELECT * FROM study_groups WHERE id=?',id).first();let mailSent=true;try{await accountGroupMail(env,g,u);}catch{mailSent=false;}return accountJSON({id,mailSent},201);}
 if(path==='/api/grupos/entrar'){await accountRate(env,'join:'+u.id,10,900);const token=accountText(b.token,100),password=accountPassword(b.password),g=await accountQuery(env,'SELECT * FROM study_groups WHERE invite_hash=?',await digest(token)).first();if(!g||!await accountPasswordMatches(password,g.password_hash))throw new Failure(400,'Link ou senha do grupo incorretos.');const id=g.id+'|'+u.id,member=await accountQuery(env,'SELECT status FROM group_members WHERE id=?',id).first();if(member?.status==='blocked')throw new Failure(403,'O criador removeu seu acesso a este grupo.');if(!member)await accountQuery(env,'INSERT INTO group_members (id,group_id,user_id,status,requested_at) VALUES (?,?,?,?,?)',id,g.id,u.id,'pending',now()).run();return accountJSON({ok:true,status:member?.status||'pending',name:g.name});}
 const match=path.match(/^\/api\/grupos\/([\w-]+)\/(aprovar|recusar|remover|convite|reenviar|sair)$/);if(match){const [,id,action]=match;if(action==='sair'){const g=await accountGroup(env,id,u);if(g.owner_id===u.id)throw new Failure(400,'O criador permanece responsável pelo grupo.');await accountQuery(env,'DELETE FROM group_members WHERE id=?',id+'|'+u.id).run();return accountJSON({ok:true});}const g=await accountGroup(env,id,u,true);if(['aprovar','recusar','remover'].includes(action)){const target=accountText(b.userId,80);if(target===u.id)throw new Failure(400,'Você não pode remover o criador do grupo.');if(action==='aprovar')await accountQuery(env,"UPDATE group_members SET status='approved' WHERE id=? AND status='pending'",id+'|'+target).run();else await accountQuery(env,"UPDATE group_members SET status='blocked' WHERE id=?",id+'|'+target).run();return accountJSON({ok:true});}if(action==='convite'){const invite=random(32),password=accountPassword(b.password);await accountQuery(env,'UPDATE study_groups SET password_hash=?,invite_hash=?,invite_secret=? WHERE id=?',await accountHash(password),await digest(invite),await seal(invite,env),id).run();}const fresh=await accountQuery(env,'SELECT * FROM study_groups WHERE id=?',id).first();let mailSent=true;try{await accountGroupMail(env,fresh,u);}catch{mailSent=false;}return accountJSON({ok:true,mailSent});}
 throw new Failure(404,'Página não encontrada.');
 }catch(error){if(!(error instanceof Failure))console.error('account_operation_failed',path,error.name||'Error');return accountJSON({error:error instanceof Failure?error.message:'Não foi possível concluir. Tente novamente.'},error instanceof Failure?error.status:503);}}
